version: '3.2'

services:
  server:
    build:
      context: ./server
    ports:
      - 3000:3000 
    environment:
    - PUBSUB_HOST=${PUBSUB_HOST}
    - PUBSUB_SECRET=${PUBSUB_SECRET}
    - PUBSUB_HUB=Demo_hub
    - RACK_ENV=production
  ui:
    build:
      context: ./client
    ports:
      - 80:8080